#! /bin/sh

# variables
	gap=10
	PANEL_HEIGHT=30
	
	export gap
	export PANEL_HEIGHT

# colors
	b0=$(xrdb -query | grep "background" | cut -f2 | head -n 1)
	f0=$(xrdb -query | grep "foreground" | cut -f2 | head -n 1)
	c0=$(xrdb -query | grep "color0" | cut -f2 | head -n 1)
	c1=$(xrdb -query | grep "color1" | cut -f2 | head -n 1)
	c2=$(xrdb -query | grep "color2" | cut -f2 | head -n 1)
	c3=$(xrdb -query | grep "color3" | cut -f2 | head -n 1)
	c4=$(xrdb -query | grep "color4" | cut -f2 | head -n 1)
	c5=$(xrdb -query | grep "color5" | cut -f2 | head -n 1)
	c6=$(xrdb -query | grep "color6" | cut -f2 | head -n 1)
	c7=$(xrdb -query | grep "color7" | cut -f2 | head -n 1)
	c8=$(xrdb -query | grep "color8" | cut -f2 | head -n 1)

# gap
	bspc config window_gap      $gap

# padding
	bspc config top_padding     $($PANEL_HEIGHT -$gap)
	bspc config right_padding   -$gap
	bspc config bottom_padding  -$gap
	bspc config left_padding    -$gap

# monocle
	bspc config gapless_monocle     false # needed because of negative padding
	bspc config borderless_monocle  true
	bspc config single_monocle      true

# border
	bspc config border_width 1 
	bspc config normal_border_color $b0
	bspc config active_border_color $c2
	bspc config focused_border_color $c2
	bspc config presel_feedback_color $c2

# pointer
	bspc config focus_follows_pointer true
	bspc config pointer_follows_focus false

# split
	bspc config split_ratio 0.5

# monitor conf
	#bspc monitor -d 一 二 三 四 五 六 七 八 九 十
	bspc monitor DVI-I-1 -d 一 二 三 四 五 六
	bspc monitor DP-1 -d 七 八 九 十

# rules
	#states
	bspc rule -a spotify 	state=pseudo_tiled
	bspc rule -a conky 	sticky=on manage=off lower=on
	bspc rule -a firefox 	private=on
	bspc rule -a atom 	private=on
	bspc rule -a dmsw 	state=floating
	bspc rule -a bb 	state=floating


	# desktops
	bspc rule -a firefox 	desktop='^7'
	bspc rule -a spotify 	desktop='^10'
	bspc rule -a mattermost desktop='^9'
	bspc rule -a discord 	desktop='^9'

# launch polybar
	$HOME/.config/polybar/launch.sh
